### ISSUE TITLE
server_profile update doesnt modify the values 

### ISSUE THREAD

**Issue by crkg** [HewlettPackard/oneview-python#102]
I'm writing exactly what I am trying to modify on the server profile. this is executed on the IDE. 

i'm setting the server profile to set managed manually , and the update doesnt reflect the required settings. 

server_profile["firmware"]={u'firmwareBaselineUri': "", u'manageFirmware': False, u'forceInstallFirmware': False, u'firmwareInstallType': ""}

server_profile.update(force=True)

Please help to fix the issue.

**Comment by AsisBagga** [comment]
@crkg Hi, the information you have shared is not sufficient for me to understand the issue, could you please elaborate.

Could you please share the error you get, your python script, and the what version of the Python OneviewSDK and Oneview Appliance are you using?

With the above details i can see you haven't provided any firmware to get installed. 
```server_profile["firmware"]={'firmwareBaselineUri': "" u'manageFirmware': False, u'forceInstallFirmware': False, u'firmwareInstallType': ""}```

**firmwareBaselineUri:** Identifies the firmware baseline to be applied to the server hardware. Server firmware is not modified if 'manageFirmware' is false.

**Comment by AsisBagga** [comment]
@crkg Hi, following up on last updates, do you have any new updates to the issue? 
Please let us know if your query is addressed.

**Comment by AsisBagga** [comment]
@crkg Hi, Since we haven't received update with regards to our response so far, we are planning to close the issue at this time. 
Please feel free to reopen or open new issue anytime ,  we are more than happy to support.
