### ISSUE TITLE
Missing methods in certificate_authority.py

### ISSUE THREAD

**Issue by karthikvr1** [HewlettPackard/oneview-python#115]
Hi, 
I would like to highlight that there are missing methods in the file hpeOneView/resources/security/certificate_authority.py in release 5.5.0; The get_all() method is missing which is used in the example scmb.py. 
The code present in the github is different from the one present in the release bundle 5.5.0. Please find attached pics for reference. 

We have fixed this issue internally but wanted to highlight. Thanks. 

Regards,
Karthik VR (141karthik@gmail.com / karthik.vr@hpe.com)

![get_all_method_present_in_github](https://user-images.githubusercontent.com/16410056/104459684-1133cd00-55d3-11eb-863b-83c1983fc72a.png)
![get_all_method_absent_in_release_5 5 0](https://user-images.githubusercontent.com/16410056/104459687-12fd9080-55d3-11eb-9020-478880407e33.png)

**Comment by VenkateshRavula** [comment]
@karthikvr1, The get_all() method in certificate_authority library and scmb.py example are added post 5.5.0 release. 
These changes comes under unreleased section for now and will be part of next SDK release i.e., 5.6.0.
For your info, you can check that SDK 5.5.0 is released on 4th November 2020 and the get_all() method is added on 5th December 2020.

**Comment by karthikvr1** [comment]
@VenkateshRavula.. Thanks for the clarification.
