### ISSUE TITLE
New Hardware needs attachment to existing SCOPE and PROFILE

### ISSUE THREAD

**Issue by zeshan1977** [HewlettPackard/oneview-python#139]
2 Questions

I create new server_hardware(iLO IP) in a oneview instance.
I need to attach above to existing SCOPE=FOO_SCOPE and Server Profile="FOO_SVR_PROFILE"
I am confused as to How do I go about doing this?

Do I first Create the empty server hardware without a profile and a scope and then added or do I create a server with the scope in the profile attached as per the options list below
each object has too many Uris??

<PRE>
  
server_hardwares = oneview_client.server_hardware
   # Create a rack-mount server
      options = {
         "hostname": config['server_hostname'],
         "username": config['server_username'],
         "password": config['server_password'],
         "licensingIntent": "OneView",
         "configurationState": "Managed",
         "scopesUri":'/rest/FOO_SCOPES/Uri",
         "serverProfileUri":'/rest/FOO_SVR_PROFILE/Uri"
      }
    try:
        server = server_hardwares.add(options)
        print("Issue: added  successfully!")
    except Exception as ex:
        print("Issue: ERROR: Can't add "+server_name+" ")
        pprint(str(ex))
        sys.exit()
</PRE>
or do I create thr empty server hardware resource and then
find "what" uri?what is resource_uri_1
and attach it to the FOO_SCOPE
<PRE>
        print("\n## Update the scope resource assignments, adding two resources")
        options = {
            "addedResourceUris": [resource_uri_1, resource_uri_2]
        }
        scopes.update_resource_assignments(scope['uri'], options)
        print("  Done.")

**Comment by VenkateshRavula** [comment]
@zeshan1977 , Please follow the second method. Add server hardware and get its uri (```uri1```), create profile and get its uri (```uri2```). Now add both these uris (```uri1, uri2```) to the scope while create or update.

```
   # Create a rack-mount server
      options = {
         "hostname": config['server_hostname'],
         "username": config['server_username'],
         "password": config['server_password'],
         "licensingIntent": "OneView",
         "configurationState": "Managed",
         "scopesUri":'/rest/FOO_SCOPES/Uri",
         "serverProfileUri":'/rest/FOO_SVR_PROFILE/Uri"
      }
```
when you tried to add server hardware using the above payload, it may fail because there are few attributes (```scopesUri``` & ```serverProfileUri```) which are not supported by server hardware ```add()``` method. So please remove such unsupported attributes from payloads and proceed by creating individual resources and fetching their Uris and then updating/adding those resourceUris to the scope.

**Comment by zeshan1977** [comment]
Hi, 
Sorry you say create_profile. This is not what I am trying to do

"when you tried to add server hardware using the above payload, it may faiL
IT DOES FAIL"

 because there are few attributes (scopesUri & serverProfileUri) which are not supported by server hardware add() method. So please remove such unsupported attributes from payloads and proceed by creating
I DO CREATE A NEW SERVER HARDWARE

 individual resources and fetching their Uris and then updating/adding those resourceUris to the scope.
ABOVE STATEMENT I NOT CLEAR . I NEED A SAMPLE PIECE OF CODE. the examples are not clear


i) I add a new server hardware to OV--->OK
ii) I need to attach it to already existing profile
iii) I need to atach it to already existing SCOPE

How Exactly do I go about doing that, could you provide some sample , MAKE SURE YOU GIVE IN YOUR SAMPLE actual key names

**Comment by VenkateshRavula** [comment]
Hi @zeshan1977, You cannot attach a ```serverProfile``` to a server hardware while adding it. But you can attach a ```scope``` to server hardware while adding it by providing ```initialScopeUris``` in server hardware payload which is the list of scopes.
Once server hardware is added, you can fetch the ```serverHardwareUri``` and ```serverHardwareTypeUri``` of new hardware and update your server profile with the new hardware details. 

I have attached the sample code which worked for me. Please give a try and close this issue if it helps.

[test_issue.txt](https://github.com/HewlettPackard/oneview-python/files/6204313/test_issue.txt)

**Comment by zeshan1977** [comment]
Thanks Venkatesh
see  below
<PRE>
scope uri: '/rest/scopes/22162aa5-850d-4b82-881b-ecd84a842fb4'
Added rack mount server 'ILO2M20050BV3.fsillab.ford.com'.
  uri = '/rest/server-hardware/37393150-3032-4D32-3230-303530425633'
Traceback (most recent call last):
  File "github_issue_139.py", line 75, in <module>
    server_profile = server_profile.update(profile_payload)
  File "/Users/mzeshan/opt/anaconda3/lib/python3.7/site-packages/hpeOneView/resources/resource.py", line 67, in wrap
    return obj(*args, **kwargs)
  File "/Users/mzeshan/opt/anaconda3/lib/python3.7/site-packages/hpeOneView/resources/servers/server_profiles.py", line 102, in update
    self.data = self._helper.update(resource, uri, force, timeout)
  File "/Users/mzeshan/opt/anaconda3/lib/python3.7/site-packages/hpeOneView/resources/resource.py", line 480, in update
    return self.do_put(uri, resource, timeout, custom_headers)
  File "/Users/mzeshan/opt/anaconda3/lib/python3.7/site-packages/hpeOneView/resources/resource.py", line 786, in do_put
    return self._task_monitor.wait_for_task(task, timeout)
  File "/Users/mzeshan/opt/anaconda3/lib/python3.7/site-packages/hpeOneView/resources/task_monitor.py", line 82, in wait_for_task
    task_response = self.__get_task_response(task)
  File "/Users/mzeshan/opt/anaconda3/lib/python3.7/site-packages/hpeOneView/resources/task_monitor.py", line 142, in __get_task_response
    raise HPEOneViewTaskError(msg, error_code)
hpeOneView.exceptions.HPEOneViewTaskError: The selected server hardware does not appear to have an integrated SAS controller.
</PRE>


My code.
I need your help with the complete payload as I cannot find documentation on what to do?

Also I need help with removing the added hardware as this server will have a profile attached to it.
so from what I have done in the UI it is . DETACHING the profile from the server hardware and then removing it.

<PRE>
from pprint import pprint
from hpeOneView.oneview_client import OneViewClient
from hpeOneView.exceptions import HPEOneViewException

config = {
    "ip": "XX.XX.XX.XX", #OneView IP
    "credentials": {
        "userName":"administrator",#OneView admin user
        "password":"XXXXX", #oneview passwd
        "authLoginDomain":"Local"
    },
    "server_hostname":"XX.XX.XX.XX", #The iLO ip
    "server_username":"hp", #The iLO uid admin level
    "server_password":"abcd1234"#the iLO uid's passwd
}

variant = 'C7000'
options = {
    "hostname": config['server_hostname'],
    "username": config['server_username'],
    "password": config['server_password'],
    "licensingIntent": "OneView",
    "configurationState": "Managed"
}

# variable declaration
server_name = config['server_hostname']
scope_name = 'Mohammed-TEST-S-WINDOWS'
profile_name = 'Mohammed-TEST-P-WINDOWS'

oneview_client = OneViewClient(config)
server_hardwares = oneview_client.server_hardware
scopes = oneview_client.scopes
server_profiles = oneview_client.server_profiles

# Get scope uri by name
scope_uri = scopes.get_by_name(scope_name).data['uri']
print("scope uri: '{}'".format(scope_uri))

# Add initialScopeUris to server hardware payload
options["initialScopeUris"] = [scope_uri]

# Add server hardware with scope uri
server = server_hardwares.get_by_name(server_name)
if not server and variant == 'C7000':
   # This is only supported on appliance which support rack mounted servers
   server = server_hardwares.add(options)
   print("Added rack mount server '{}'.\n  uri = '{}'".format(server.data['name'], server.data['uri']))

   # Fetch server hardware uri and hardware type uri and create a dictionary
   sh_uri = server.data['uri']
   sht_uri = server.data['serverHardwareTypeUri']

   profile_payload = dict(serverHardwareUri=sh_uri, serverHardwareTypeUri=sht_uri)

   # Update profile with new hardware
   server_profile = server_profiles.get_by_name(profile_name)
   server_profile = server_profile.update(profile_payload)
   print("Updated server profile '{}'".format(server_profile.data['name']))
else:
   print(server_name+" Already Exist")

**Comment by VenkateshRavula** [comment]
Hi @zeshan1977 , it seems like your existing server profile is having a local storage configured and is expecting a SAS controller in the new server hardware. But you may be trying to attach a server hardware which is not having SAS controller and hence the error. 
Can you please share your server profile configuration so that it helps me to understand the issue better.

**Comment by zeshan1977** [comment]
ok thnx, I understand. closing this issue
