### ISSUE TITLE
Server Hardware Module - Add multiple servers

### ISSUE THREAD

**Issue by AnushaY1916** [HewlettPackard/oneview-python#15]
### Scenario/Intent
Getting error while adding multiple servers. 

### Environment Details
 - **OneView SDK Version:** 5.0.0
 - **OneView Appliance Version:** 5.0
 - **OneView Client API Version:** [API version listed in your configuration file or dictionary]
 - **Python Version:** 2.7.17
 - **Platform:** Ubuntu

Server gets added but the return type for the method is not proper and throws an error.

**Comment by VenkateshRavula** [comment]
This is not an issue in python SDK. This is an issue in ansible SDK. We have to fix this in ansible library.
