### ISSUE TITLE
In OneView _  How do I get a list of scopes attached to the server profile not to the server hardware?

### ISSUE THREAD

**Issue by zeshan1977** [HewlettPackard/oneview-python#156]
<PRE>
OK.    oneview_client = OneViewClient(config)
OK   scopes = oneview_client.scopes
OK    server_hardwares = oneview_client.server_hardware
OK    server_profile_templates = oneview_client.server_profile_templates
OK   server_profiles = oneview_client.server_profiles
Not OK.. server_profille_list = server_profile.scopes 

******************
From Looking at the 
URI value it appears as if they are one and  the same, yet in the GUI we are able to set a scope 
Server_Hardware > Scope="foo_scope"
Server_Hardware>server_profile> Scope ??? .HOW DO WE access this?

*******************
</PRE>

**Comment by VenkateshRavula** [comment]
You can use ```get_scope_resource``` method which is available in scopes resource.

```
oneview_client = OneViewClient(config)
scopes = oneview_client.scopes

profile_uri = "/rest/server-profiles/xxxxxxx"
sp_scopes = scopes.get_scope_resource(profile_uri)
pprint(sp_scopes.data['scopeUris'])
```

**Comment by zeshan1977** [comment]
I see thanks, I will test it out .For Now Closing the issue
