### ISSUE TITLE
Unable ro get session key when user is using Active Direc authentication

### ISSUE THREAD

**Issue by zeshan1977** [HewlettPackard/oneview-python#159]
Hello
As per article : https://developer.hpe.com/blog/curling-through-the-oneview-api

I am trying to get the session key
USERID=abcna1\\$admid
Our admin id are prefaced with $ signs
And  the way we login is LOCATION follow with a backslash follow with a $ sign follow with a userid all concatenated
so CALIF1\\$admidca

<PRE>
 sessionID=$(curl -s -k -H "accept: application/json" -H "content-type: application/json" -d "{\"authLoginDomain\":\"ABC.com\",\"userName\":\"ABCna1\\$admid\",\"password\":\"abcdq234!345\"}" -X POST https://10.10.10.10/rest/login-sessions)
 
</PRE>
By the way when this is run on the GUI , it works just fine

Exact Error:
<PRE>
{"errorCode":"MALFORMED_JSON","message":"Malformed JSON cannot be parsed.","details":"The JSON sent in the request is malformed and cannot be parsed. There is a problem on line 1 near column -1.","recommendedActions":["Correct the malformed JSON and retry the request."],"errorSource":null,"nestedErrors":[],"data":{}}

**Comment by yuvirani** [comment]
@zeshan1977, Thanks for raising this issue, we are looking into this.

**Comment by yuvirani** [comment]
@zeshan1977, I was able to reproduce the error with the above command. The symbol $ is used for variables in bash shell and yes, when you use strings with $, you need to provide it inside quotes.

Since your username is $admid, it must be changed to " ' $admid ' "

Please try the below command and let us know if it works fine.

 sessionID=$(curl -s -k -H "accept: application/json" -H "content-type: application/json" -d "{\"authLoginDomain\":\"ABC.com\",\"userName\":\"ABCna1\\"'$admid'"\",\"password\":\"abcdq234!345\"}" -X POST https://10.10.10.10/rest/login-sessions)

**Comment by zeshan1977** [comment]
I hae tried what do suggest and I still get the same error as mentioned in my earlier comment

**Comment by yuvirani** [comment]
@zeshan1977,

We have done more analysis and noticed that our Oneview has certain restrictions in which userName cant have $ in it. So, we are not able to test the username with $ from our side. But, we have used Active Diecrtory and came up the working command. Please try and update us if it worked.

When you provide authLoginDomain attribute, ".com" is not required, also \\\\ has to be there in userName("ABCna1\\\\"'$admid'") for json formatting.

```
sessionID=$(curl -s -k -H "accept: application/json" -H "content-type: application/json" -d "{\"authLoginDomain\":\"ABC\",\"userName\":\"ABCna1\\\\"'$admid'"\",\"password\":\"abcdq234!345\"}" -X POST https://10.10.10.10/rest/login-sessions)
```

**Comment by zeshan1977** [comment]
Code
<PRE>
#!/bin/bash


ONEVIEW_IP="10.10.10.10"
PWD=\"Q3T4\!fubar\"
JQ="jq"

# Tihs is the only escaping that works
USER=\"ABCna1\\'$admin1'\"

echo $USER
echo $PWD

curl -s -k -H "accept: application/json" -H "content-type: application/json" -d "{\"authLoginDomain\":\"abc\",\"userName\":$USER,\"password\":$PWD}" -X POST https://$ONEVIEW_IP/rest/login-sessions

</PRE>

Error
<PRE>
"errorCode":"INVALID_JSON_MAPPING","message":"JSON cannot be parsed.","details":"The JSON in the request is not valid. There is a problem on line 1 near column 38.","recommendedActions":["Correct the invalid JSON and retry the request."],"errorSource":null,"nestedErrors":[],"data":{}}
</PRE>
