### ISSUE TITLE
HPEOneViewTaskError: The selected server hardware does not appear to have an integrated SAS controller.

### ISSUE THREAD

**Issue by shivendra1296** [HewlettPackard/oneview-python#165]
We are using ansible for Assigning profiles to Servers using HPOneView and in that we are frequently getting the error that server hardware does not appear to have any integreated SAS controller.
{"changed": false, "module_stderr": "/usr/lib/python2.7/site-packages/hpeOneView-5.4.0-py2.7.egg/hpeOneView/__init__.py:47: Warning: Running unsupported Python version: 2.7.5, unexpected errors might occur. Use of Python v2.7.9+ is advised.\nTraceback (most recent call last):\n  File \"/home/ibmadm/.ansible/tmp/ansible-tmp-1625899104.61-8027-179377823515946/AnsiballZ_oneview_server_profile.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/ibmadm/.ansible/tmp/ansible-tmp-1625899104.61-8027-179377823515946/AnsiballZ_oneview_server_profile.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ibmadm/.ansible/tmp/ansible-tmp-1625899104.61-8027-179377823515946/AnsiballZ_oneview_server_profile.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.oneview_server_profile', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib64/python2.7/runpy.py\", line 176, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib64/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_oneview_server_profile_payload_lEqRzF/ansible_oneview_server_profile_payload.zip/ansible/modules/oneview_server_profile.py\", line 670, in <module>\n  File \"/tmp/ansible_oneview_server_profile_payload_lEqRzF/ansible_oneview_server_profile_payload.zip/ansible/modules/oneview_server_profile.py\", line 666, in main\n  File \"/tmp/ansible_oneview_server_profile_payload_lEqRzF/ansible_oneview_server_profile_payload.zip/ansible/module_utils/oneview.py\", line 475, in run\n  File \"/tmp/ansible_oneview_server_profile_payload_lEqRzF/ansible_oneview_server_profile_payload.zip/ansible/modules/oneview_server_profile.py\", line 280, in execute_module\n  File \"/tmp/ansible_oneview_server_profile_payload_lEqRzF/ansible_oneview_server_profile_payload.zip/ansible/modules/oneview_server_profile.py\", line 320, in __present\n  File \"/tmp/ansible_oneview_server_profile_payload_lEqRzF/ansible_oneview_server_profile_payload.zip/ansible/modules/oneview_server_profile.py\", line 449, in __create_profile\n  File \"build/bdist.linux-x86_64/egg/hpeOneView/resources/servers/server_profiles.py\", line 74, in create\n    resource_data = self._helper.create(data, timeout=timeout, force=force)\n  File \"build/bdist.linux-x86_64/egg/hpeOneView/resources/resource.py\", line 430, in create\n    return self.do_post(uri, data, timeout, custom_headers)\n  File \"build/bdist.linux-x86_64/egg/hpeOneView/resources/resource.py\", line 765, in do_post\n    return self._task_monitor.wait_for_task(task, timeout)\n  File \"build/bdist.linux-x86_64/egg/hpeOneView/resources/task_monitor.py\", line 82, in wait_for_task\n    task_response = self.__get_task_response(task)\n  File \"build/bdist.linux-x86_64/egg/hpeOneView/resources/task_monitor.py\", line 142, in __get_task_response\n    raise HPEOneViewTaskError(msg, error_code)\nHPEOneViewTaskError: The selected server hardware does not appear to have an integrated SAS controller.\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

We are manually able to create the RAID and SAS controller is working fine. Please if you could help in troubleshooting this issue.

**Comment by VenkateshRavula** [comment]
Hi @shivendra1296, Currently we don't support SAS controller resource in our python SDK.

Please provide me the below requested info to help you better.
1. Did you see any warning message in oneview UI while creation the server profile(with same configuration) manually..?
2. What is the python SDK version you are using..?
3. If profile creation on UI is giving any warning message, the please try the below steps.
Try server profile create using ```force=True``` argument. 
```profile = server_profiles.create(profile_payload, force=True)```

**Comment by VenkateshRavula** [comment]
We are closing this issue since we didn't hear back from you. Please feel free to reopen this issue.
