### ISSUE TITLE
hpeOneView.resources.servers.server_profiles.ServerProfiles GET PROBLEM

### ISSUE THREAD

**Issue by Le-Syl21** [HewlettPackard/oneview-python#184]
Hi,

I'm using:  hpeOneView 6.3.0

here is my code:

`
#!/usr/bin/python3
from pprint import pprint
from hpeOneView.oneview_client import OneViewClient
from hpeOneView.exceptions import HPEOneViewException
config = {
        'ip': '#####',
        'credentials': {
        'userName': '#####',
        'password': '#####'
        }
}
oneview_client = OneViewClient(config)
server_hardwares = oneview_client.server_hardware
server_profils = oneview_client.server_profiles
print('===== GET PROFIL ON ACTIF HARDWARE BY URL =====')
for server in server_hardwares.get_by('powerState', 'on'):
        pprint(server_profils.get_by_uri(server.get('serverProfileUri')))

print('===== GET PROFIL BY Profile UUID =====')
for server in server_hardwares.get_by('powerState', 'on'):
        profiluuid=server.get('serverProfileUri').split('/')[-1]
        print('FOUND UUID IS: '+profiluuid)
        print(server_profils.get_by('profileUUID', profiluuid))
`

Here is my output:
`
===== GET PROFIL ON ACTIF HARDWARE BY URL =====
<hpeOneView.resources.servers.server_profiles.ServerProfiles object at 0x7f18851eab00>
<hpeOneView.resources.servers.server_profiles.ServerProfiles object at 0x7f18853dcc88>
<hpeOneView.resources.servers.server_profiles.ServerProfiles object at 0x7f18851eaf60>
<------ I HAVE REDUCE OUPUT------>
<hpeOneView.resources.servers.server_profiles.ServerProfiles object at 0x7f18853dcc88>
<hpeOneView.resources.servers.server_profiles.ServerProfiles object at 0x7f18851eaeb8>
<hpeOneView.resources.servers.server_profiles.ServerProfiles object at 0x7f18852fffd0>
<hpeOneView.resources.servers.server_profiles.ServerProfiles object at 0x7f18851eadd8>
===== GET PROFIL BY Profile UUID =====
FOUND UUID IS: 8ce89e8a-8775-4806-af4a-a1cbc28ca99f
Traceback (most recent call last):
  File "./hpe.py", line 23, in <module>
    print(server_profils.get_by('profileUUID', profiluuid))
  File "/home/nfs/sgargasson/.local/lib/python3.6/site-packages/hpeOneView/resources/resource.py", line 244, in get_by
    results = self.get_all(filter=filter)
  File "/home/nfs/sgargasson/.local/lib/python3.6/site-packages/hpeOneView/resources/resource.py", line 157, in get_all
    result = self._helper.get_all(start=start, count=count, filter=filter, sort=sort)
  File "/home/nfs/sgargasson/.local/lib/python3.6/site-packages/hpeOneView/resources/resource.py", line 421, in get_all
    return self.do_requests_to_getall(uri, count, custom_headers=custom_headers)
  File "/home/nfs/sgargasson/.local/lib/python3.6/site-packages/hpeOneView/resources/resource.py", line 765, in do_requests_to_getall
    response = self._connection.get(uri, custom_headers=custom_headers)
  File "/home/nfs/sgargasson/.local/lib/python3.6/site-packages/hpeOneView/connection.py", line 347, in get
    raise HPEOneViewException(body)
hpeOneView.exceptions.HPEOneViewException: ('An unexpected problem occurred while performing this operation.', {'errorCode': None, 'message': 'An unexpected problem occurred while performing this operation.', 'details': '', 'messageParameters': [], 'recommendedActions': ['Please retry the operation. If the problem persists, contact your authorized support representative and provide a support dump.'], 'errorSource': None, 'nestedErrors': [], 'data': {}})
`

As you can see when I search a profil by is uri, it returns me an entire PROFILES object

As you can see when I try on profile UUID it crash...

I'm avaiable if you want a Remote DEBUG

**Comment by chebroluharika** [comment]
Hi @Le-Syl21,
Thanks for reaching out to us.
Please use 'uuid' inplace of 'profileUUID' as a filter string in get_by operation since they both are equally same.
For reference,
oneview_client = OneViewClient(config)
server_hardwares = oneview_client.server_hardware
server_profils = oneview_client.server_profiles
print('===== GET PROFIL ON ACTIF HARDWARE BY URL =====')
for server in server_hardwares.get_by('powerState', 'on'):
pprint(server_profils.get_by_uri(server.get('serverProfileUri')))

print('===== GET PROFIL BY Profile UUID =====')
for server in server_hardwares.get_by('powerState', 'on'):
profiluuid=server.get('serverProfileUri').split('/')[-1]
print('FOUND UUID IS: '+profiluuid)
print(server_profils.get_by('uuid', profiluuid))

Do let us know if you still face any issues.

**Comment by Le-Syl21** [comment]
Hi,

Already try that but some profile doesn't have UUID so my output can be empty like that:

/rest/scopes/resources/rest/server-profiles/89c1b540-81ea-4171-a11b-949935fc3fa5', 'serviceManager': None, 'eTag': '1594212920820/134', 'refreshState': 'NotRefreshing'}]
FOUND UUID IS: 4e1bb93c-13e2-41f7-9520-e2e324dcee5e
[]
FOUND UUID IS: d968d2a6-84da-4ba9-b9df-c7e45b038c77
[]
FOUND UUID IS: 2b1a0767-5c18-45ba-b60f-439ed8bbcd06
[{'type': 'ServerProfileV12', 'uri': '/rest/server-profiles/2b1a0767-5c18-45ba-b60f-439ed8bbcd06', 'profileUUID': '2b1a0767-5c18-45ba-b60f-439ed8bbcd06', 'name':

**Comment by Le-Syl21** [comment]
As I show you some running hardware server can't obtain the attached profil.
Some UUID give you data and other just []

**Comment by Le-Syl21** [comment]
INPUT:
`oneview_client = OneViewClient(config)
hardwares = oneview_client.server_hardware
profils = oneview_client.server_profiles
print('===== GET PROFIL ON ACTIF HARDWARE BY URL =====')
for server in hardwares.get_by('powerState', 'on'):
        print('HARDWARE=> '+server.get('platform')+' / '+server.get('model')+' serverProfileUri: '+server.get('serverProfileUri'))
        for profil in profils.get_all():
                for k, v in profil.items():
                    if v == server.get('serverProfileUri'):
                        print('\tPROFIL=> '+k+' = '+v)
                    if v == server.get('serverProfileUri').split('/')[-1]:
                        print('\tPROFIL=> '+k+' = '+v)
`
OUPUT:
`HARDWARE=> BladeServer / ProLiant BL460c G7 serverProfileUri: /rest/server-profiles/96c1d1fa-1eb2-428e-bb39-29a9f1e567cd
        PROFIL=> uri = /rest/server-profiles/96c1d1fa-1eb2-428e-bb39-29a9f1e567cd
        PROFIL=> profileUUID = 96c1d1fa-1eb2-428e-bb39-29a9f1e567cd
        PROFIL=> uuid = 96c1d1fa-1eb2-428e-bb39-29a9f1e567cd
HARDWARE=> BladeServer / ProLiant BL460c G7 serverProfileUri: /rest/server-profiles/63625510-6517-4d6d-92a7-eab38310a12e
        PROFIL=> uri = /rest/server-profiles/63625510-6517-4d6d-92a7-eab38310a12e
        PROFIL=> profileUUID = 63625510-6517-4d6d-92a7-eab38310a12e
`
As you can see on my exemple every profil get an uri or profileUUID but uuid is not present all times.
Maybe have you a command to refresh all profils  ???

**Comment by Le-Syl21** [comment]
OK after a deep look inside all profile get uuid but it's not always the same as end of uri.

So profils.get_by(uri, input) or profils.get_by_uri(input) don't work

So to make it work, I need to do the durty job be myself:

```
oneview_client = OneViewClient(config)
hardwares = oneview_client.server_hardware
profils = oneview_client.server_profiles
print('===== GET PROFIL ON ACTIF HARDWARE BY URL =====')
for server in hardwares.get_by('powerState', 'on'):
        print('HARDWARE=> '+server.get('platform')+' / '+server.get('model')+' serverProfileUri: '+server.get('serverProfileUri'))
        for profil in profils.get_all():
                if profil.get('uri') == server.get('serverProfileUri'):
                        pprint(profil)
```

**Comment by chebroluharika** [comment]
Hi @Le-Syl21 
Seems to be error fixed for you. 
please let us know if we can help further
