### ISSUE TITLE
How to access firmware component  names and version num assigned to the current FW bundle in the HPE Hardware?

### ISSUE THREAD

**Issue by zeshan1977** [HewlettPackard/oneview-python#192]
I want to know which is the current bundle appplied to my Hardware.
What are the ComponentNames and what are there Versions. w.r.t to the bundle

I tried to use, https://github.com/HewlettPackard/oneview-python/blob/master/examples/firmware_drivers.py
but it only gives me  the information on the drivers. NOT what i want

<PRE>
Get list of firmwares managed by the appliance.
- HPE_Synergy_Custom_SPP_202005_2020_05_15_ILO233
- HPE Synergy Custom SPP 202005 2020 05 15
- Service Pack for Synergy
- Custom__SSP_2021_02_02_BIOS250_ILO244
- HPE_Synergy_Custom_SPP_201903_2019_05_14_with_ILO_146_and_BIOS_204
- HPE Synergy 480 Gen10 (I42) Compute Module firmware
- HPE Synergy 480 Gen10 (I42) Compute Module firmware
- </PRE>

**Comment by chebroluharika** [comment]
Hi @zeshan1977,
You can get component version and component names of firmware attached to Server Hardware using rest/server-hardware/{id}/firmware and please use the below snippet satisfying the same requirement.
    # Get a Firmware by Server Hardware ID
    print("Get a Firmware by Server Hardware ID")
    p = server.get_firmware()
    pprint(p)
Please let us know if this helps.

**Comment by zeshan1977** [comment]
is id an integer?

**Comment by chebroluharika** [comment]
Hi @zeshan1977,
Please use 
    server = server_hardwares.get_by_name(servers[0])
    print(server.data)
from server.data, you will get serverProfileUri, then using serverProfileUri and using below snippet you will get SPP details of a firmware attached to hardware.
all_profiles = server_profiles.get_all()
print("\nGet a server profile that matches the specified uri")
if all_profiles:
    profile_uri = server.data['serverProfileUri']
    profile = server_profiles.get_by('uri', profile_uri)
    print('  %s' % profile.data['firmware'])

**Comment by zeshan1977** [comment]
lasst line above in your sample code

    print(' %s' % profile.data['firmware'])
AttributeError: 'list' object has no attribute 'data

**Comment by chebroluharika** [comment]
Oh sorry,
Please try with profile[‘firmware’]

**Comment by zeshan1977** [comment]
I tried that as well.
profile is a Empty List -->[]
???????

**Comment by zeshan1977** [comment]
when I print server.data
I get output a dict.
What I think I need is this(--->)
how can I access that via the python SDK

--->   'serverFirmwareInventoryUri': '/rest/server-hardware/39313738-3034-584D-5139-32353034534C/firmware',
       'serverGroupUri': '/rest/enclosure-groups/2f2b7d86-f862-459a-8c2b-e73e18408145',
       'serverHardwareTypeUri': '/rest/server-hardware-types/DBC27CB4-02EA-4938-9F0B-581CFD44E85E',
       'serverName': 'phyxxx.prod.XXXX',

**Comment by chebroluharika** [comment]
Hi @zeshan1977 ,
Can you please make me understand whether you are getting serverProfileUri from server.data, you should have an active serverProfile attached to serverHardware to get that attribute.
If you have active serverProfile and firmware attached to the given servername then, you should get firmware details from below snippet.

server = server_hardwares.get_by_name('server_name')
active_profile_uri = server.data['serverProfileUri']

# Get by uri
print("\nGet a server profile by uri")
profile = server_profiles.get_by_uri(active_profile_uri)
print(profile.data['firmware'])

**Comment by zeshan1977** [comment]
Thank You
