### ISSUE TITLE
firmware drivers does not have standard method get_by_uri and get_by_name

### ISSUE THREAD

**Issue by DungKHoang** [HewlettPackard/oneview-python#20]
oneview_client.firmware_drivers does not support get_by_name nor get_by_uri

Example of code:
  \ thisfw = oneview_client.firmware_drivers.get_by_uri('/rest/firmware-drivers/SPP_2018_11_20190405_for_HPE_Synergy_Z7550-96678')
AttributeError: 'FirmwareDrivers' object has no attribute 'get_by_uri'

**Comment by VenkateshRavula** [comment]
Provided support for the requested methods in latest release. v5.2.0
