### ISSUE TITLE
Support for socks5 type proxy

### ISSUE THREAD

**Issue by arthurzenika** [HewlettPackard/oneview-python#235]
I can see that one can configure a proxy with `export ONEVIEWSDK_PROXY='<proxy_host>:<proxy_port>'` or `proxy` in the config dictionary or JSON. But it seems that there is no way to configure a socks5 proxy. 

Would you welcome a contribution to enable this use case ?

**Comment by nabhajit-ray** [comment]
Hi @arthurzenika ,

Yeah currently we are not supporting the socks5 proxy. It would be great if you can contribute to support this. Please raise a pull request and once reviewed, it can be added to the main branch.

**Comment by alisha-k-kalladassery** [comment]
Hi @arthurzenika ,

We are closing this issue as we haven't heard back from you. Please feel free to open a new issue if you have any queries.

Thanks

**Comment by arthurzenika** [comment]
Sorry for not getting back, the project I am working on prioritized another item so the oneview data had to wait. I will contribute a patch in the coming months. 

Here is a dirty patch I did when I was stuck : 

```diff 
diff --git a/hpeOneView/connection.py b/hpeOneView/connection.py
index 2db0e5e9..c41de809 100644
--- a/hpeOneView/connection.py
+++ b/hpeOneView/connection.py
@@ -38,6 +38,7 @@ import logging
 import shutil  # for shutil.copyfileobj()
 import mmap  # so we can upload the iso without having to load it in memory
 import os
+import socks
 import ssl
 import time
 import traceback
@@ -233,6 +234,9 @@ class connection(object):
                                                    context=context,
                                                    timeout=self._timeout)
                 conn.set_tunnel(self._host, 443)
+                conn.sock = socks.socksocket() # manually set socket
+                # TODO : make this configurable
+                conn.sock.set_proxy(socks.PROXY_TYPE_SOCKS5, "127.0.0.1", 8123) # use socks proxy address
         else:
             context.verify_mode = ssl.CERT_NONE
             if self._doProxy is False:
```

This obviously needs reworking.

**Comment by alisha-k-kalladassery** [comment]
Hi @arthurzenika ,

Please raise a PR once you are ready with the code. We will review it and take it forward.

Thanks
