### ISSUE TITLE
EthernetNetworks Update does not work

### ISSUE THREAD

**Issue by Georgimi** [HewlettPackard/oneview-python#81]
I tried the update method provided in the examples.

This should get a specific network by name and edit its purpose to Management

_ethernet_network = oneview_client.ethernet_networks.get_by_name(network_entered)
ethernet_data = ethernet_network.data
ethernet_data['purpose'] = "Management"
ethernet_network.update(ethernet_data)_

Actually it runs and edits the ethernet_data to the correct new values
e.g. a print shows new values

{'type': 'ethernet-networkV4', 'uri': '/rest/ethernet-networks/d35197eb-5014-4ba2-8733-04f014f1d9ab', 'category': 'ethernet-networks', 'eTag': '9f1eb265-c956-47f0-8d24-441089a20246', 'created': '2020-08-25T10:40:53.928Z', 'modified': '2020-08-25T10:40:53.939Z', 'scopesUri': '/rest/scopes/resources/rest/ethernet-networks/d35197eb-5014-4ba2-8733-04f014f1d9ab', 'vlanId': 777, 'subnetUri': None, 'ipv6SubnetUri': None, 'connectionTemplateUri': '/rest/connection-templates/f427b030-f590-49e1-b2dd-1d9328d6e631', 'privateNetwork': False, 'smartLink': False, **'purpose': 'Management',** 'ethernetNetworkType': 'Tagged', 'fabricUri': '/rest/fabrics/3ce1cfbd-d577-485a-9b63-a3556b11a3ad', 'description': None, 'state': 'Active', 'status': 'OK', 'name': 'networkfromCSVone'}

The update runs as well. I can see in OneView a new Activity Task.
But it shows 

Update | 8/25/20  1:49:47 pm15 minutes ago | Completed1s | Administrator
No changes are detected during an edit operation. The resource is not changed.

If i do another grep of the ethernet_data right after the update I can see the data unchanged ...
{'type': 'ethernet-networkV4', 'uri': '/rest/ethernet-networks/d35197eb-5014-4ba2-8733-04f014f1d9ab', 'category': 'ethernet-networks', 'eTag': '9f1eb265-c956-47f0-8d24-441089a20246', 'created': '2020-08-25T10:40:53.928Z', 'modified': '2020-08-25T10:40:53.939Z', 'scopesUri': '/rest/scopes/resources/rest/ethernet-networks/d35197eb-5014-4ba2-8733-04f014f1d9ab', 'vlanId': 777, 'subnetUri': None, 'ipv6SubnetUri': None, 'connectionTemplateUri': '/rest/connection-templates/f427b030-f590-49e1-b2dd-1d9328d6e631', 'privateNetwork': False, 'smartLink': False, **'purpose': 'General'**, 'ethernetNetworkType': 'Tagged', 'fabricUri': '/rest/fabrics/3ce1cfbd-d577-485a-9b63-a3556b11a3ad', 'description': None, 'state': 'Active', 'status': 'OK', 'name': 'networkfromCSVone'}

I tried with name and vlaniD instead ... same result.

**Comment by chebroluharika** [comment]
Hi @Georgimi , 
Thanks for pointing out the issue. We are working on it and fix will be available in a couple of days.

**Comment by chebroluharika** [comment]
Please feel free to reopen the issue if you still feels issue is present even after working with master branch.
