### ISSUE TITLE
Change Password Sample?

### ISSUE THREAD

**Issue by DanRobinsonHPE** [HewlettPackard/oneview-python#91]
Could you add some simple examples on how to change passwords?

If they are different, I have 2 in mind.
Change MY Password (change password of the account you just connected with)
Change YOUR Password (change password of an account other than the one you logged in with)

Thanks,
Dan

https://techlibrary.hpe.com/docs/enterprise/servers/oneview5.0/cicf-api/en/index.html#rest/users

**Comment by chebroluharika** [comment]
Hi @DanRobinsonHPE,
Thank you for bringing up this enhancement request. We are working on this and this feature will be available from next release.
